// src/routes/login/+page.svelte
<script lang="ts">
  import { supabase } from '$lib/supabaseClient';
  import { Button } from 'flowbite-svelte';

  async function signInWithDiscord() {
    const { error } = await supabase.auth.signInWithOAuth({
      provider: 'discord',
    });
    if (error) {
      console.error('Error signing in with Discord:', error.message);
    }
  }
</script>

<div class="flex flex-col items-center justify-center min-h-screen">
  <div class="w-full max-w-sm p-8 space-y-4 bg-white rounded-lg shadow-md">
    <h2 class="text-2xl font-bold text-center">Login</h2>
    <Button on:click={signInWithDiscord} class="w-full">
      Login with Discord
    </Button>
  </div>
</div>

// src/app/pages/login.vue
<template>
  <div class="flex flex-col items-center justify-center min-h-screen py-12">
    <UCard class="w-full max-w-sm">
      <template #header>
        <h2 class="text-2xl font-bold text-center">Login</h2>
      </template>

      <div class="flex flex-col items-center space-y-4">
        <UButton
          icon="i-simple-icons-discord"
          size="lg"
          color="primary"
          variant="solid"
          label="Login with Discord"
          :loading="loading"
          @click="signInWithDiscord"
        />
      </div>
    </UCard>
  </div>
</template>

<script setup lang="ts">
const supabase = useSupabaseClient();
const loading = ref(false);

const signInWithDiscord = async () => {
  loading.value = true;
  const { error } = await supabase.auth.signInWithOAuth({
    provider: 'discord',
    options: {
      redirectTo: window.location.origin + '/confirm',
    },
  });

  if (error) {
    console.error(error);
    alert(error.message);
  }
  loading.value = false;
};
</script>
