// src/routes/admin/feeds/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Button, Modal, Card, Badge, Table, TableBody, TableBodyCell, TableBodyRow, TableHead, TableHeadCell } from 'flowbite-svelte';
  import type { PageData } from './$types';
  import FeedEditor from '$lib/components/Admin/FeedEditor.svelte';

  export let data: PageData;

  let feeds = data.feeds || [];
  let isFeedEditorOpen = false;
  let editingFeed = null;

  const openFeedEditor = () => {
    editingFeed = null;
    isFeedEditorOpen = true;
  };

  const editFeed = (feed) => {
    editingFeed = { ...feed };
    isFeedEditorOpen = true;
  };

  const deleteFeed = async (feedId) => {
    if (confirm('Are you sure you want to delete this feed?')) {
      const response = await fetch(`/api/feeds/${feedId}`, { method: 'DELETE' });
      if (response.ok) {
        feeds = feeds.filter(f => f.id !== feedId);
      } else {
        alert('Error deleting feed');
      }
    }
  };

  const handleFeedSubmit = async (event) => {
    const feedData = event.detail;
    const url = editingFeed ? `/api/feeds/${editingFeed.id}` : '/api/feeds';
    const method = editingFeed ? 'PUT' : 'POST';

    const response = await fetch(url, {
      method,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(feedData),
    });

    if (response.ok) {
      isFeedEditorOpen = false;
      const updatedFeed = await response.json();
      if (editingFeed) {
        const index = feeds.findIndex(f => f.id === editingFeed.id);
        feeds[index] = updatedFeed;
      } else {
        feeds = [...feeds, updatedFeed];
      }
    } else {
      alert('Error saving feed');
    }
  };
</script>

<div class="container mx-auto p-4">
  <h2 class="text-xl font-bold mb-4">Admin Feeds Page</h2>
  <Button on:click={openFeedEditor}>Add New Feed</Button>

  <Table>
    <TableHead>
      <TableHeadCell>Name</TableHeadCell>
      <TableHeadCell>URL</TableHeadCell>
      <TableHeadCell>Enabled</TableHeadCell>
      <TableHeadCell>Tags</TableHeadCell>
      <TableHeadCell>Actions</TableHeadCell>
    </TableHead>
    <TableBody>
      {#each feeds as feed (feed.id)}
        <TableBodyRow>
          <TableBodyCell>{feed.name}</TableBodyCell>
          <TableBodyCell>{feed.url}</TableBodyCell>
          <TableBodyCell>
            <Badge color={feed.enabled ? 'green' : 'red'}>{feed.enabled ? 'Enabled' : 'Disabled'}</Badge>
          </TableBodyCell>
          <TableBodyCell>
            {#each feed.tags as tag (tag.id)}
              <Badge class="mr-1 mb-1">{tag.name}</Badge>
            {/each}
          </TableBodyCell>
          <TableBodyCell>
            <Button on:click={() => editFeed(feed)}>Edit</Button>
            <Button color="red" on:click={() => deleteFeed(feed.id)}>Delete</Button>
          </TableBodyCell>
        </TableBodyRow>
      {/each}
    </TableBody>
  </Table>

  <Modal bind:open={isFeedEditorOpen}>
    <Card>
      <h3 class="text-lg font-semibold">{editingFeed ? 'Edit Feed' : 'Add New Feed'}</h3>
      <FeedEditor feed={editingFeed} on:submit={handleFeedSubmit} on:cancel={() => isFeedEditorOpen = false} />
    </Card>
  </Modal>
</div>

// src/app/pages/admin/feeds.vue
<template>
  <div>
    <NuxtLayout name="admin">
      <h2 class="text-xl font-bold mb-4">Admin Feeds Page</h2>
      <UButton icon="i-lucide-plus" label="Add New Feed" @click="openFeedEditor" class="mb-4" />
      <AdminFeedDataTable :feeds="feeds" :pending="pending" @edit="editFeed" @delete="deleteFeed" />

      <UModal v-model="isFeedEditorOpen">
        <UCard>
          <template #header>
            <h3 class="text-lg font-semibold">{{ editingFeed ? 'Edit Feed' : 'Add New Feed' }}</h3>
          </template>
          <AdminFeedEditor
            :feed="editingFeed"
            @submit="handleFeedSubmit"
            @cancel="closeFeedEditor"
          />
        </UCard>
      </UModal>
    </NuxtLayout>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useSupabaseClient } from '#imports';

const supabase = useSupabaseClient();

const isFeedEditorOpen = ref(false);
const editingFeed = ref(null);

const { data: feeds, pending, refresh } = useAsyncData('admin-feeds', async () => {
  const { data, error } = await supabase
    .from('feeds')
    .select('*, tags(*)');

  if (error) {
    throw new Error(error.message);
  }
  return data;
});

const openFeedEditor = () => {
  editingFeed.value = null;
  isFeedEditorOpen.value = true;
};

const closeFeedEditor = () => {
  isFeedEditorOpen.value = false;
  editingFeed.value = null;
};

const editFeed = (feed) => {
  editingFeed.value = { ...feed };
  isFeedEditorOpen.value = true;
};

const deleteFeed = async (feedId) => {
  if (confirm('Are you sure you want to delete this feed?')) {
    const { error } = await supabase
      .from('feeds')
      .delete()
      .eq('id', feedId);

    if (error) {
      alert(error.message);
    } else {
      refresh();
    }
  }
};

const handleFeedSubmit = async (feedData) => {
  if (editingFeed.value) {
    // Update existing feed
    const { error } = await supabase
      .from('feeds')
      .update({ name: feedData.name, url: feedData.url, enabled: feedData.enabled })
      .eq('id', editingFeed.value.id);

    if (error) {
      alert(error.message);
    } else {
      // Update feed_tags
      await updateFeedTags(editingFeed.value.id, feedData.tags);
      refresh();
      closeFeedEditor();
    }
  } else {
    // Add new feed
    const { data, error } = await supabase
      .from('feeds')
      .insert({ name: feedData.name, url: feedData.url, enabled: feedData.enabled })
      .select();

    if (error) {
      alert(error.message);
    } else {
      // Insert feed_tags
      if (data && data.length > 0) {
        await updateFeedTags(data[0].id, feedData.tags);
      }
      refresh();
      closeFeedEditor();
    }
  }
};

const updateFeedTags = async (feedId, tags) => {
  // Delete existing feed_tags for this feed
  await supabase.from('feed_tags').delete().eq('feed_id', feedId);

  // Insert new feed_tags
  if (tags && tags.length > 0) {
    const feedTagsToInsert = tags.map(tagId => ({ feed_id: feedId, tag_id: tagId }));
    const { error } = await supabase.from('feed_tags').insert(feedTagsToInsert);
    if (error) {
      console.error('Error updating feed tags:', error);
    }
  }
};
</script>
