// src/app/pages/login.vue
<template>
  <div class="flex flex-col items-center justify-center min-h-screen py-12">
    <UCard class="w-full max-w-sm">
      <template #header>
        <h2 class="text-2xl font-bold text-center">Login</h2>
      </template>

      <div class="flex flex-col items-center space-y-4">
        <UButton
          icon="i-simple-icons-discord"
          size="lg"
          color="primary"
          variant="solid"
          label="Login with Discord"
          :loading="loading"
          @click="signInWithDiscord"
        />
      </div>
    </UCard>
  </div>
</template>

<script setup lang="ts">
const supabase = useSupabaseClient();
const loading = ref(false);

const signInWithDiscord = async () => {
  loading.value = true;
  const { error } = await supabase.auth.signInWithOAuth({
    provider: 'discord',
    options: {
      redirectTo: window.location.origin + '/confirm',
    },
  });

  if (error) {
    console.error(error);
    alert(error.message);
  }
  loading.value = false;
};
</script>

// src-old/src/routes/login/+page.svelte
<script lang="ts">
	import { Button } from 'flowbite-svelte';
	import { supabase } from '$lib/supabaseClient';

	async function signInWithDiscord() {
		await supabase.auth.signInWithOAuth({
			provider: 'discord',
			options: {
				redirectTo: `${window.location.origin}/auth/callback`
			}
		});
	}
</script>

<div class="flex h-screen items-center justify-center">
	<div class="w-full max-w-md rounded-lg border p-8 text-center shadow-md">
		<h1 class="mb-4 text-2xl font-bold">Welcome to RSS-D-GENM</h1>
		<p class="mb-6 text-gray-600">Please sign in to continue</p>
		<Button onclick={signInWithDiscord} size="lg">Sign In with Discord</Button>
	</div>
</div>
